name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  PROJECT_NAME: high-concurrency-ticketing-api
  DOCKER_IMAGE: sunjaegood/high-concurrency-ticketing-api:dev
  S3_BUCKET_PATH: s3://high-concurrency-ticketing/dev
  APP_DIR: /home/ec2-user/app

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Image Build
        run: docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: Docker Image Push
        run: docker push ${{ env.DOCKER_IMAGE }}

      - name: Get AWS Deploy Permission by OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.PROJECT_NAME }}-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload Files to S3
        run: |
          aws s3 cp docker-compose.yml ${{ env.S3_BUCKET_PATH}}/docker-compose.yml --region ${{env.AWS_REGION }}

      - name: Deploy to EC2 by SSM
        run: |
          aws ssm send-command \
          --region ${{ env.AWS_REGION }} \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Project,Values=${{ env.PROJECT_NAME }}" \
          --parameters 'commands=[
            "mkdir -p ${{ env.APP_DIR }}",
            "aws s3 cp ${{ env.S3_BUCKET_PATH }}/docker-compose.yml ${{ env.APP_DIR }}/docker-compose.yml --region ${{ env.AWS_REGION }}",
            "aws ssm get-parameter --name /${{ env.PROJECT_NAME }}/dev/ENV_FILE --with-decryption --region ${{ env.AWS_REGION }} --query Parameter.Value --output text > ${{ env.APP_DIR }}/.env",
            "cd ${{ env.APP_DIR }}",
            "sudo docker compose pull",
            "sudo docker compose up -d --remove-orphans"
          ]'